apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data-01
  namespace: dev-dev-01
  labels:
    ketches/app: nginx
    ketches/edition: '1750994117445'
    ketches/owned: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Mi
    requests:
      storage: 2Mi
  volumeName: pvc-bc91d7f3-bdf2-4bd7-bfe8-a4cf94ad69a1
  storageClassName: local-path
  volumeMode: Filesystem