// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/space.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ketches/ketches/internal/model"
)

// MockSpaceService is a mock of SpaceService interface.
type MockSpaceService struct {
	ctrl     *gomock.Controller
	recorder *MockSpaceServiceMockRecorder
}

// MockSpaceServiceMockRecorder is the mock recorder for MockSpaceService.
type MockSpaceServiceMockRecorder struct {
	mock *MockSpaceService
}

// NewMockSpaceService creates a new mock instance.
func NewMockSpaceService(ctrl *gomock.Controller) *MockSpaceService {
	mock := &MockSpaceService{ctrl: ctrl}
	mock.recorder = &MockSpaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpaceService) EXPECT() *MockSpaceServiceMockRecorder {
	return m.recorder
}

// AddMembers mocks base method.
func (m *MockSpaceService) AddMembers(ctx context.Context, req *model.AddMembersRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMembers", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMembers indicates an expected call of AddMembers.
func (mr *MockSpaceServiceMockRecorder) AddMembers(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMembers", reflect.TypeOf((*MockSpaceService)(nil).AddMembers), ctx, req)
}

// Create mocks base method.
func (m *MockSpaceService) Create(ctx context.Context, req *model.CreateSpaceRequest) (*model.CreateSpaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*model.CreateSpaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSpaceServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSpaceService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockSpaceService) Delete(ctx context.Context, space string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, space)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSpaceServiceMockRecorder) Delete(ctx, space interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSpaceService)(nil).Delete), ctx, space)
}

// Get mocks base method.
func (m *MockSpaceService) Get(ctx context.Context, space string) (*model.GetSpaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, space)
	ret0, _ := ret[0].(*model.GetSpaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSpaceServiceMockRecorder) Get(ctx, space interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSpaceService)(nil).Get), ctx, space)
}

// List mocks base method.
func (m *MockSpaceService) List(ctx context.Context) (*model.ListSpacesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(*model.ListSpacesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSpaceServiceMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSpaceService)(nil).List), ctx)
}

// ListMembers mocks base method.
func (m *MockSpaceService) ListMembers(ctx context.Context, space string) (*model.ListSpaceMembersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, space)
	ret0, _ := ret[0].(*model.ListSpaceMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockSpaceServiceMockRecorder) ListMembers(ctx, space interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockSpaceService)(nil).ListMembers), ctx, space)
}

// RemoveMembers mocks base method.
func (m *MockSpaceService) RemoveMembers(ctx context.Context, req *model.RemoveSpacesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMembers", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMembers indicates an expected call of RemoveMembers.
func (mr *MockSpaceServiceMockRecorder) RemoveMembers(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMembers", reflect.TypeOf((*MockSpaceService)(nil).RemoveMembers), ctx, req)
}

// Update mocks base method.
func (m *MockSpaceService) Update(ctx context.Context, req *model.UpdateSpaceRequest) (*model.UpdateSpaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*model.UpdateSpaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSpaceServiceMockRecorder) Update(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSpaceService)(nil).Update), ctx, req)
}
