---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: additional-role
rules:
- apiGroups:
  - ""
  resources:
  - limitranges
  - resourcequotas
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  - ingressclasses
  verbs:
  - "get"
  - "list"
  - "watch"
