# permissions for end users to view applicationgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: applicationgroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ketches
    app.kubernetes.io/part-of: ketches
    app.kubernetes.io/managed-by: kustomize
  name: applicationgroup-viewer-role
rules:
- apiGroups:
  - core.ketches.io
  resources:
  - applicationgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.ketches.io
  resources:
  - applicationgroups/status
  verbs:
  - get
