apiVersion: v1
kind: Namespace
metadata:
  name: ketches-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ketches
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ketches-sa
    namespace: wt-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ketches
  namespace: ketches-system
---    
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ketches
  namespace: ketches-system
spec:
  selector:
    matchLabels:
      app: ketches
  template:
    metadata:
      labels:
        app: ketches
    spec:
      serviceAccountName: ketches
      containers:
      - name: controller
        image: pescox/ketches:v0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ketches
  namespace: ketches-system
spec:
  selector:
    app: ketches
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
            