apiVersion: core.ketches.io/v1alpha1
kind: Space
metadata:
  labels:
    app.kubernetes.io/name: space
    app.kubernetes.io/instance: space-sample
    app.kubernetes.io/part-of: ketches
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ketches
  name: space-sample
spec:
  displayName: "Pone's Space"
  # TODO(user): Add fields here
