apiVersion: core.ketches.io/v1alpha1
kind: Extension
metadata:
  labels:
    app.kubernetes.io/name: extension
    app.kubernetes.io/instance: extension-sample
    app.kubernetes.io/part-of: ketches
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ketches
  name: extension-sample
spec:
  # TODO(user): Add fields here
