// Code generated by "stringer -type=AuditSourceKey -output=audit_source_key_string.go"; DO NOT EDIT.

package global

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuditSourceKeyPlatform-0]
	_ = x[AuditSourceKeyApplication-1]
	_ = x[AuditSourceKeySpace-2]
}

const _AuditSourceKey_name = "AuditSourceKeyPlatformAuditSourceKeyApplicationAuditSourceKeySpace"

var _AuditSourceKey_index = [...]uint8{0, 22, 47, 66}

func (i AuditSourceKey) String() string {
	if i < 0 || i >= AuditSourceKey(len(_AuditSourceKey_index)-1) {
		return "AuditSourceKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuditSourceKey_name[_AuditSourceKey_index[i]:_AuditSourceKey_index[i+1]]
}
